services:
  taskflow-back:
    image: taskflow-back-end
    container_name: taskflow-back
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back-end/src:/app/src
      - ./back-end/tasks.json:/app/tasks.json
    networks:
      - taskflow-network
  taskflow-front:
    image: taskflow-front-end
    container_name: taskflow-front
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
    depends_on:
      - taskflow-back
    networks:
      - taskflow-network
networks:
  taskflow-network:
    driver: bridge